### ISSUE TITLE
Landing one row above target when starting from topmost row, leftmost column

### ISSUE THREAD

**Issue by butwerenotthereyet** [IngoMeyer441/tmux-easy-motion#10]
Fill the history with more than a screen of text:
![0](https://user-images.githubusercontent.com/58348703/106231058-9f987900-61a5-11eb-9149-678be6921eba.png)
Scroll to the top and move to the far left:
![1](https://user-images.githubusercontent.com/58348703/106231061-a45d2d00-61a5-11eb-90b1-7f1f872b6cec.png)
Prepare to target a letter:
![2](https://user-images.githubusercontent.com/58348703/106231068-a9ba7780-61a5-11eb-9dd6-19cf00e46157.png)
Target a letter that appears more than once (in the image, `r`):
![3](https://user-images.githubusercontent.com/58348703/106231076-ade69500-61a5-11eb-9a86-f686af2d8d84.png)
If there are multiple target letters, press the first (in the image, `x`):
![4](https://user-images.githubusercontent.com/58348703/106231081-b343df80-61a5-11eb-899e-a590cf424163.png)
Press the final target letter (in the image, `y`):
![5](https://user-images.githubusercontent.com/58348703/106231093-b8089380-61a5-11eb-928a-620d926dbd3d.png)
Land one row above the targeted letter (in the image, the `o` above the targeted `r`)

**Comment by IngoMeyer441** [comment]
For me, `tmux-easy-motion` does not work at all if starting from the topmost row, leftmost column :astonished: I have to debug this first...

**Comment by butwerenotthereyet** [comment]
Yeah 😅 I think difference might be if you run `tmux clear`.  Without you get behavior you see.

**Comment by IngoMeyer441** [comment]
Commit 8308bd1c66541bb8cc0c3978c9a24389b7eb68f9 fixes that no jump target is displayed at all. But I cannot reproduce the behavior you describe. Is it maybe also fixed with 8308bd1c66541bb8cc0c3978c9a24389b7eb68f9?

**Comment by butwerenotthereyet** [comment]
No, it still happens to me.  Did you try use long lines in the text file so that they wrap when running cat?  Does it happen for you if you set your shell's `PS1` to `$` before following the steps in https://github.com/IngoMeyer441/tmux-easy-motion/issues/10#issue-796561785 ?

```
$ tmux -V
tmux next-3.3
$ cat ~/test.conf
run-shell "~/tmux-easy-motion/easy_motion.tmux"
set -g default-shell /bin/bash
set-option -g status-right ''
$ cat .bash-profile
export PS1=$
$ #to launch tmux:
$ tmux -L test -f ~/test.conf
```

**Comment by IngoMeyer441** [comment]
Thanks, I could reproduce it now. The tmux command `start-of-line` behaves differently for wrapped text if the cursor is already on the left-most column (in that case the cursor is set to the beginning of the wrapped line and causes the wrong row offset in your example). Commit b395c45e54de2907bdef6abe1da48844dab93e1a adds a column check and only executes `start-of-line` if the cursor is not in the first column.

**Comment by butwerenotthereyet** [comment]
That fixed it, thank you!!
